# Generated by Django 3.1.7 on 2021-03-18 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('toppings', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserHotDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.IntegerField(null=True)),
                ('is_favorite', models.BooleanField(null=True)),
                ('note', models.CharField(max_length=100, null=True)),
                ('is_approved', models.BooleanField(null=True)),
                ('hot_dog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogfightapi.hotdog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
