# Generated by Django 3.1.7 on 2021-03-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogfightapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotdog',
            name='image',
            field=models.CharField(max_length=10),
        ),
    ]
