# Generated by Django 3.1.7 on 2021-03-12 17:11

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dogfightapi', '0002_auto_20210312_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhotdog',
            name='date_completed',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True),
        ),
    ]
