# Generated by Django 3.1.7 on 2021-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogfightapi', '0003_auto_20210312_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhotdog',
            name='date_completed',
            field=models.IntegerField(),
        ),
    ]
