# Generated by Django 3.1.7 on 2021-03-12 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogfightapi', '0004_auto_20210312_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhotdog',
            name='date_completed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userhotdog',
            name='hot_dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogfightapi.hotdog'),
        ),
        migrations.AlterField(
            model_name='userhotdog',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userhotdog',
            name='is_favorite',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userhotdog',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
